import Head from "next/head";
import React from "react";
import DesktopMenu from "./DesktopMenu";
import styles from "../../styles/Home.module.scss";
import Image from "next/image";
import { Popbutton } from "./Popbutton";

interface Props {
  title?: string;
}

export default function Layout(props: React.PropsWithChildren<Props>) {
  return (
    <div
      style={{
        overflow: "auto",
        height: window.innerHeight,
        scrollBehavior: "smooth",
      }}
      id="main"
    >
      <Head>
        <title>{props.title ? props.title : "AKASHA"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DesktopMenu />
      <div className="content">{props.children}</div>
      <footer className={styles.footer}>
        <div>
          <a href="#" target="_blank" rel="noopener noreferrer">
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
          <p
            style={{
              width: "55%",
              color: "#f3f3f3",
              margin: "auto",
              marginTop: "0.2rem",
              textAlign: "center",
            }}
          >
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Vero
            officiis, porro sequi corporis accusantium voluptas quos iusto
            obcaecati vel. Fugit nemo molestias id nihil velit aliquid ipsa
            itaque reiciendis rem. Lorem ipsum dolor, sit amet consectetur
            adipisicing elit. Vero officiis, porro sequi corporis accusantium
          </p>
        </div>
      </footer>
      <Popbutton />
    </div>
  );
}
